# Generated by Django 3.1 on 2020-08-27 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_new_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='new',
            name='image',
        ),
    ]
