# Generated by Django 3.1 on 2020-08-27 09:40

from django.db import migrations
import easy_thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_remove_new_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='new',
            name='image',
            field=easy_thumbnails.fields.ThumbnailerImageField(null=True, upload_to='images/%Y/%m/%d/'),
        ),
    ]
