# Generated by Django 3.1 on 2020-09-03 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_new_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='new',
            name='short_body',
            field=models.TextField(null=True),
        ),
    ]
